### ISSUE TITLE
 Clarification Needed on BindInterface API Example in Depinject Documentation

### ISSUE THREAD

**Issue by akaladarshi** [cosmos/cosmos-sdk-docs#118]
Description:

Found a potential typo in the depinject docs regarding `func(duck Duck) APond`. It's unclear what `APond` refers to in the examples provided at [v0.50](https://docs.cosmos.network/v0.50/build/packages/depinject#bindinterface-api), [v0.47](https://docs.cosmos.network/v0.47/build/packages/depinject#bindinterface-api) and [main](https://docs.cosmos.network/main/build/packages/depinject#bindinterface-api). Can this be clarified or corrected?.
I'm raising this issue instead of directly submitting a PR because the potential typo appears in three different versions.

**Comment by tac0turtle** [comment]
APond would be the returned value for inputting a duck, it is only an example of how it could be used, it should not be copied. Does this help or?

**Comment by akaladarshi** [comment]
I got little bit confused because it was written `return Pond{Duck: duck}`.  So i thought it might be a typo.
Thanks for clarification.
