### ISSUE TITLE
Typo in learn section of docs

### ISSUE THREAD

**Issue by nidhi-singh02** [cosmos/cosmos-sdk-docs#179]
There's a typo in the learn section for version v0.50 https://docs.cosmos.network/v0.50/learn

<img width="1184" alt="image" src="https://github.com/user-attachments/assets/3f79dabd-b074-4b84-aa4b-7180659ffc98">

Seems the last commit made 3 months ago corrected the typo in the change, not sure why is it not getting reflected on the website ? May be that update is not deployed on this version ?

**Comment by julienrbrt** [comment]
Hey, i think the typo hasn't been fixed in the release/v0.50.x version of the SDK.

**Comment by nidhi-singh02** [comment]
Ohh, in the [repo](https://github.com/cosmos/cosmos-sdk-docs), I couldn't find any corresponding tag for v0.50.x, so not sure how fix it ? Wondering how it is deployed for release/v0.50.x

**Comment by julienrbrt** [comment]
It is in this repo: https://github.com/cosmos/cosmos-sdk
