### ISSUE TITLE
landing pages for each section 

### ISSUE THREAD

**Issue by tac0turtle** [cosmos/cosmos-sdk-docs#57]

**Comment by samricotta** [comment]
Can you give a little more detail on this? In previous epic, we had  `Add user journeys for chain developers and users on the landing page`. This is definitely something that needs to be done but is this what you are referring to? Or maybe its in addition...

**Comment by tac0turtle** [comment]
noam gave the feedback that each page should have a page that users land on instead of the current way of opening a page in the list of pages
